In [1]:
def double(x):
    """ Double x """
    return 2*x
#Executing this return statement completes execution of the double function’s body and 
#computes the value of the call expression.

In [7]:
from datascience import *
import matplotlib
path_data = '../../data/'
matplotlib.use('Agg', warn=False)
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import numpy as np
np.set_printoptions(threshold=50)
from datascience import *
import numpy as np
path_data = '../../../../data/'
import matplotlib
matplotlib.use('Agg', warn=False)
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)

from urllib.request import urlopen 
import re
def read_url(url): 
    return re.sub('\\s+', ' ', urlopen(url).read().decode())

In [8]:
double(17)
#The expressions above is called  call expressions. 

34

In [9]:
double(-0.6/4)

-0.3

In [10]:
any_name = 42
double(any_name)

84

In [11]:
double(make_array(3, 4, 5))


array([ 6,  8, 10])

In [12]:
double([3,4,5])
#see this behvaior is different from above

[3, 4, 5, 3, 4, 5]

DOCSTRING
In Python, this is called a docstring — a description of its behavior and expectations about its arguments. The docstring can also show example calls to the function, where the call is preceded by >>>
Docstrings are typically defined using triple quotation marks at the start and end, which allows a string to span multiple lines. The first line is conventionally a complete but short description of the function, while following lines provide further guidance to future users of the function.

In [15]:
#Example
def percent(x, total):
    """Convert x to a percentage of total.
    
    More precisely, this function divides x by total,
    multiplies the result by 100, and rounds the result
    to two decimal places.
    
    >>> percent(4, 16)
    25.0
    >>> percent(1, 6)
    16.67
    """
    return round((x/total)*100, 2)

In [16]:
percent?

In [17]:

percent(33, 200)

16.5

In [18]:
def percents(counts):
    """Convert the values in array_x to percents out of the total of array_x."""
    total = counts.sum()
    return np.round((counts/total)*100, 2)
#this time replacing round by np.round because the argument is an array and not a number.



In [19]:
some_array = make_array(7, 10, 4)
percents(some_array)

array([33.33, 47.62, 19.05])

In [20]:
def biggest_difference(array_x):
    """Find the biggest difference in absolute value between two adjacent elements of array_x."""
    diffs = np.diff(array_x)
    absolute_diffs = abs(diffs)
    return max(absolute_diffs)

In [22]:
some_numbers = make_array(2, 4, 5, 6, 4, -1, 1)
big_diff = biggest_difference(some_numbers)
print("The biggest difference is", big_diff)



The biggest difference is 5


In [23]:
def percents(counts, decimal_places=2):
    """Convert the values in array_x to percents out of the total of array_x."""
    total = counts.sum()
    return np.round((counts/total)*100, decimal_places)

parts = make_array(2, 1, 4)
print("Rounded to 1 decimal place:", percents(parts, 1))
print("Rounded to the default number of decimal places:", percents(parts))

Rounded to 1 decimal place: [28.6 14.3 57.1]
Rounded to the default number of decimal places: [28.57 14.29 57.14]


In [25]:
ages = Table().with_columns(
    'Person', make_array('A', 'B', 'C', 'D', 'E', 'F'),
    'Age', make_array(17, 117, 52, 100, 6, 101)
)
ages

Person | Age
A      | 17
B      | 117
C      | 52
D      | 100
E      | 6
F      | 101

# Applying a function to a column

In [26]:
def cut_off_at_100(x):
    """The smaller of x and 100"""
    return min(x, 100)

In [27]:
cut_off_at_100(31)

31

In [28]:
cut_off_at_100(131)

100

To cut off each of the ages at 100, we will use the a new Table method. The apply method calls a function on each element of a column, forming a new array of return values. 

In [29]:
ages.apply(cut_off_at_100, 'Age')
#What we have done here is apply the function cut_off_at_100 to each value in the Age column of the table ages. 
#The output is the array of corresponding return values of the function. For example, 17 stayed 17, 117 became 100, 52 stayed 52, and so on.



array([ 17, 100,  52, 100,   6, 100])

In [30]:
#adding this array as a column to the original table
ages.with_column(
    'Cut Off Age', ages.apply(cut_off_at_100, 'Age')
)

Person | Age  | Cut Off Age
A      | 17   | 17
B      | 117  | 100
C      | 52   | 52
D      | 100  | 100
E      | 6    | 6
F      | 101  | 100

In [31]:
cut_off = cut_off_at_100


In [32]:
cut_off

<function __main__.cut_off_at_100(x)>

In [33]:
galton

NameError: name 'galton' is not defined

# REGRESSION TO THE MEAN
Galton drew the graph of averages through the scatter diagram and noticed that it roughly followed a straight line. This straight line is now called the regression line and is one of the most common methods of making predictions. Galton’s friend, the mathematician Karl Pearson, used these analyses to formalize the notion of correlation.

Galton’s methods such as the one we have used here are precursors to nearest neighbor prediction methods that now have powerful applications in diverse settings. The modern field of machine learning includes the automation of such methods to make predictions based on vast and rapidly evolving datasets.



In [34]:
#GROUPING
cones = Table().with_columns(
    'Flavor', make_array('strawberry', 'chocolate', 'chocolate', 'strawberry', 'chocolate'),
    'Price', make_array(3.55, 4.75, 6.55, 5.25, 5.25)
)
cones

Flavor     | Price
strawberry | 3.55
chocolate  | 4.75
chocolate  | 6.55
strawberry | 5.25
chocolate  | 5.25

In [35]:
cones.group('Flavor')

Flavor     | count
chocolate  | 3
strawberry | 2

There are two distinct categories, chocolate and strawberry. The call to group creates a table of counts in each category. The column is called count by default, and contains the number of rows in each category.

In [36]:
#Finding a Characteristic of Each Category
#The optional second argument of group names the function that will be used to aggregate values in other columns for all of those rows.
#For instance, sum will sum up the prices in all rows that match each category.
cones.group('Flavor', sum)

Flavor     | Price sum
chocolate  | 16.55
strawberry | 8.8

In [37]:
cones.group('Flavor', max)
#tells the maximum number in the category 

Flavor     | Price max
chocolate  | 6.55
strawberry | 5.25

In [38]:
cones.where('Flavor', are.equal_to('chocolate'))


Flavor    | Price
chocolate | 4.75
chocolate | 6.55
chocolate | 5.25

In [39]:
cones.where('Flavor', are.equal_to('chocolate')).column('Price')


array([4.75, 6.55, 5.25])

In [40]:
sum(cones.where('Flavor', are.equal_to('chocolate')).column('Price'))
#This is what group is doing for each distinct value in Flavor.


16.55

In [45]:
cones_choc = cones.where('Flavor', are.equal_to('chocolate')).column('Price')
cones_strawb = cones.where('Flavor', are.equal_to('strawberry')).column('Price')

cones_strawb 


array([3.55, 5.25])

In [44]:
cones_choc

array([4.75, 6.55, 5.25])

In [46]:
grouped_cones = Table().with_columns(
    'Flavor', make_array('chocolate', 'strawberry'),
    'Array of All the Prices', make_array(cones_choc, cones_strawb)
)


In [47]:
grouped_cones
#it creates an array of each category and then find the sum of that array

Flavor     | Array of All the Prices
chocolate  | [4.75 6.55 5.25]
strawberry | [3.55 5.25]

In [48]:
price_totals = grouped_cones.with_column(
    'Sum of the Array', make_array(sum(cones_choc), sum(cones_strawb))
)
price_totals

Flavor     | Array of All the Prices | Sum of the Array
chocolate  | [4.75 6.55 5.25]        | 16.55
strawberry | [3.55 5.25]             | 8.8

In [49]:
cones.group('Flavor', max)
#Once again, group creates arrays of the prices in each Flavor category. But now it finds the max of each array

Flavor     | Price max
chocolate  | 6.55
strawberry | 5.25