In [4]:
from datascience import *
baseline_high = 14.48
highs = make_array(baseline_high - 0.880, baseline_high - 0.093,
                   baseline_high + 0.105, baseline_high + 0.684)
highs

array([13.6  , 14.387, 14.585, 15.164])

Collections allow us to pass multiple values into a function using a single name. For instance, the sum function computes the sum of all values in a collection, and the len function computes its length.

In [5]:
sum(highs)/len(highs)

14.434000000000001

Arrays can also contain strings or other types of values, but a single array can only contain a single kind of data. (It usually doesn’t make sense to group together unlike data anyway.) 

In [10]:
english_parts_of_speech = make_array("noun", "pronoun", "verb", "adverb", "adjective", "conjunction", "preposition", "interjection")
english_parts_of_speech


array(['noun', 'pronoun', 'verb', 'adverb', 'adjective', 'conjunction',
       'preposition', 'interjection'], dtype='<U12')

In [13]:
type(english_parts_of_speech)


numpy.ndarray

In [14]:
eng = [2,4,6]

In [15]:
type(eng)

list

In [16]:
baseline_high = 14.48
highs = make_array(baseline_high - 0.880, 
                   baseline_high - 0.093,
                   baseline_high + 0.105, 
                   baseline_high + 0.684)
highs

array([13.6  , 14.387, 14.585, 15.164])

Arrays can be used in arithmetic expressions to compute over their contents. When an array is combined with a single number, that number is combined with each element of the array. 

In [17]:
(9/5) * highs + 32

array([56.48  , 57.8966, 58.253 , 59.2952])

Arrays also have methods, which are functions that operate on the array values. 

In [18]:
highs.size


4

In [22]:
len(highs)

4

In [23]:
highs.sum()

57.736000000000004

Each pair of parentheses in the examples below is part of a call expression; it’s calling a function with no arguments to perform a computation on the array called highs.

In [24]:
highs.mean()


14.434000000000001


The numpy package, abbreviated np in programs, provides Python programmers with convenient and powerful functions for creating and manipulating arrays

In [28]:
import numpy as np
highs

array([13.6  , 14.387, 14.585, 15.164])

For example, the diff function computes the difference between each adjacent pair of elements in an array. The first element of the diff is the second element minus the first.



In [27]:
np.diff(highs)


array([0.787, 0.198, 0.579])

In [29]:
np.cumsum(highs)

array([13.6  , 27.987, 42.572, 57.736])

In [30]:
np.arange(5)

array([0, 1, 2, 3, 4])

Notice how the array starts at 0 and goes only up to 4, not to the end value of 5.
np.arange(start, end): An array of consecutive increasing integers from start, stopping before end.
 

In [31]:
np.arange(3, 9)

array([3, 4, 5, 6, 7, 8])

np.arange(start, end, step): A range with a difference of step between each pair of consecutive values, starting from start and stopping before end.

In [32]:
np.arange(3, 30, 5)

array([ 3,  8, 13, 18, 23, 28])

In [33]:
np.arange(1.5, -2, -0.5)

array([ 1.5,  1. ,  0.5,  0. , -0.5, -1. , -1.5])

In [34]:
baseline_low = 3.00
lows = make_array(baseline_low - 0.872, baseline_low - 0.629,
                  baseline_low - 0.126, baseline_low + 0.728)
lows

array([2.128, 2.371, 2.874, 3.728])

In [35]:
baseline_high = 14.48
highs = make_array(baseline_high - 0.880, 
                   baseline_high - 0.093,
                   baseline_high + 0.105, 
                   baseline_high + 0.684)
highs

array([13.6  , 14.387, 14.585, 15.164])

In [37]:
make_array(
    highs.item(0) - lows.item(0),
    highs.item(1) - lows.item(1),
    highs.item(2) - lows.item(2),
    highs.item(3) - lows.item(3)
)


array([11.472, 12.016, 11.711, 11.436])

In [39]:
make_array(
   - highs.item(0) + lows.item(0),
    highs.item(1) - lows.item(1),
    highs.item(2) - lows.item(2),
    highs.item(3) - lows.item(3)
)



array([-11.472,  12.016,  11.711,  11.436])

In [40]:
highs - lows

array([11.472, 12.016, 11.711, 11.436])

Wallis’ Formula for  
π

In [42]:
even = np.arange(2, 1000001, 2)

even

array([      2,       4,       6, ...,  999996,  999998, 1000000])

In [44]:
one_below_even = even - 1
one_above_even = even + 1
one_below_even

array([     1,      3,      5, ..., 999995, 999997, 999999])

In [45]:
one_above_even


array([      3,       5,       7, ...,  999997,  999999, 1000001])

np.prod multiplies all the elements of an array together. https://www.inferentialthinking.com/chapters/05/3/More_on_Arrays

In [46]:
2 * np.prod(even/one_below_even) * np.prod(even/one_above_even)

3.1415910827951143

In [47]:
y = np.prod(even/one_below_even)

In [48]:
y

1253.3144506439883

In [49]:
z = np.prod(even/one_above_even)

In [50]:
z

0.001253313197330836

In [51]:
2*y*z

3.1415910827951143